### ISSUE TITLE
Demo direstory "src' is not working on my side

### ISSUE THREAD

**Issue by tramber91** [codrops/RapidImageHoverMenuEffects#3]
Hi

Thanks for your work

Curious, I have downloaded the demo (zip file) on my computer
Demo is OK with html file coming from "dist" directory but not OK from "src" directory
When I open file /src/index.html, i cannot see any menu, only an animated orange square

![ZqIOYkf 1](https://user-images.githubusercontent.com/1623843/97067674-2d216700-15c0-11eb-8a7e-c1195308456a.jpeg)

Take care

**Comment by botelho** [comment]
You need to follow the [Installation process](https://github.com/codrops/RapidImageHoverMenuEffects#installation). Running src/index.html will not work.
